Add parameters and addons from privacytools.io
allo-/firefox-profilemaker pull request #212
Opened 2020-10-05 14:06 UTC by Starli0n

Hi,

I added the missing parameters from [PrivacyTools](https://www.privacytools.io/browsers):

- privacy.trackingprotection.fingerprinting.enabled = true
- privacy.trackingprotection.cryptomining.enabled = true
- media.eme.enabled = false
- media.gmp-widevinecdm.enabled = false
- network.http.referer.XOriginTrimmingPolicy = 2
- browser.sessionstore.privacy_level = 2
- network.dns.disablePrefetchFromHTTPS = true
- network.predictor.enabled = false
- network.predictor.enable-prefetch = false

And AddOns from the same website

- [CookieAutoDelete@kennydo.xpi](https://addons.mozilla.org/firefox/downloads/file/954445/cookie_autodelete-2.2.0-an+fx.xpi)
- [Decentraleyes@ThomasRientjes.xpi](https://addons.mozilla.org/firefox/downloads/file/3539177/decentraleyes-2.0.14-an+fx.xpi)
- [ClearURLs@kevinr.xpi](https://addons.mozilla.org/firefox/downloads/file/3612592/clearurls-1.19.0-an+fx.xpi)
- [TemporaryContainers@stoically.xpi](https://addons.mozilla.org/firefox/downloads/file/3623550/temporary_containers-1.9.1-fx.xpi)
- [FirefoxMulti-AccountContainers@mozilla.org.xpi](https://addons.mozilla.org/firefox/downloads/file/3650825/firefox_multi_account_containers-7.1.0-fx.xpi)

2020-10-05 14:47 UTC, allo- requested changes
Thank you. This is a rather large commit and I see some things I would like to change.

- Try to reduce the white space changes to make the diff smaller and easier to read
- Always use the latest.xpi for addon installation (We should probably update the readme later as well)
- Try not to add redundant settings (already set by default and not likely to change in the near future) to make it easier for users to see what is changed why even when examining their profile later on.

2020-10-05 14:47 UTC, allo- commented on README.md
Looks good. In my experience decentralyes seems to interfere with other addons and I never found out why. But adding it as an optional addon is a good idea nevertheless.

For the containers there are several useful addons and some seem to interfere with each other, e.g., changing if Tabs opened from Google inside a Google container leave the container or not. It may be useful to find out which combinations work best, but starting with some container addons at all is also good. I think these four addons are nice for the generator.

2020-10-05 14:47 UTC, allo- commented on profiles/01_default.json
> -            "firstrun_tabs.json",
Is there a reason for the trailing spaces? It would be good to remove them to keep the diff readable, except there is some style guide why they should be there then we could adapt all json files.

2020-10-05 14:47 UTC, allo- commented on settings/clearurls.json
> +        "help_text": "Will automatically remove tracking elements from URLs to help protect your privacy when browsing through the Internet.",
Can you make such sentence fragments full sentences in `help_text`?

2020-10-05 14:47 UTC, allo- commented on settings/clearurls.json
> +					"install_url": "https://addons.mozilla.org/firefox/downloads/file/3612592/clearurls-1.19.0-an+fx.xpi",
Please use the "latest.xpi" URL for the enterprise policy.

2020-10-05 14:47 UTC, allo- commented on settings/decentraleyes.json
> +        "initial": true,
I am not sure if this should be enabled by default. I had some problems before and I think with addons it may be good to be conservative what's enabled by default (see what happened when uBlock got sold).
Not 100% sure, when it works it would probably be a nice addon that improves privacy without any drawbacks for the user.

2020-10-05 14:47 UTC, allo- commented on settings/media_devices.json
> +            "media.eme.enabled": false,
This does not belong here. media.navigator is about webcam support an similar media devices. And we already have settings for EME.

2020-10-05 14:47 UTC, allo- commented on settings/prefetch_next.json
> +            "network.dns.disablePrefetchFromHTTPS": true,
I think `disablePrefetchFromHTTPS` is not needed when `disablePrefetch` is set.

2020-10-05 14:47 UTC, allo- commented on settings/privacy_level.json
> +            "Store extra session data for any site. (Default starting with Firefox 4.)",
Minor: I would remove the dots as this will become combo box entries.

2020-10-05 14:47 UTC, allo- commented on settings/privacy_level.json
> +        "label": "Privacy Level"
Privacy Level is confusing for the option name as it could mean anything (and conveys it does much more) for the user.

Maybe "Sessionstore Privacy" would be better.

2020-10-05 14:47 UTC, allo- commented on settings/referer.json
> +                "network.http.referer.XOriginTrimmingPolicy": 2
This seems redundant. `XOriginPolicy: 2` disables sending a referer to another domain, so it does not matter if referers to other domains would be trimmed.

Without the change, the other changes are only whitespace changes?

2020-10-05 14:47 UTC, allo- commented on settings/temporarycontainers.json
> +					"install_url": "https://addons.mozilla.org/firefox/downloads/file/3623550/temporary_containers-1.9.1-fx.xpi",
Please use the latest.xpi

2020-10-05 14:47 UTC, allo- commented on settings/trackingprotection.json
> +            "privacy.trackingprotection.cryptomining.enabled": true
They are enabled by default anyway.

2020-10-06 08:59 UTC, Starli0n commented on README.md
Thank you

2020-10-06 09:03 UTC, Starli0n commented on profiles/01_default.json
> -            "firstrun_tabs.json",
No there is no specific reason. I activated trim trailing whitespaces in my IDE to prevent from being in this configuration for my projects. _(It is a best practice I imposed myself)_

I reviewed the spaces to let them to minimize the diff

2020-10-06 09:04 UTC, Starli0n commented on settings/clearurls.json
> +        "help_text": "Will automatically remove tracking elements from URLs to help protect your privacy when browsing through the Internet.",
Sorry, I did not get what you meant by that ?

2020-10-06 09:05 UTC, Starli0n commented on settings/clearurls.json
> +					"install_url": "https://addons.mozilla.org/firefox/downloads/file/3612592/clearurls-1.19.0-an+fx.xpi",
I made the change even for the existing ones (I did not know that it was possible)

2020-10-06 09:06 UTC, Starli0n commented on settings/decentraleyes.json
> +        "initial": true,
I disabled it by default

2020-10-06 09:07 UTC, Starli0n commented on settings/privacy_level.json
> +            "Store extra session data for any site. (Default starting with Firefox 4.)",
I removed the dots

2020-10-06 09:07 UTC, Starli0n commented on settings/privacy_level.json
> +        "label": "Privacy Level"
I changed the name of the label and the file as well

2020-10-06 09:08 UTC, Starli0n commented on settings/referer.json
> +                "network.http.referer.XOriginTrimmingPolicy": 2
Yes, there was also an unnecessary trailing `{}` that I removed

2020-10-06 09:09 UTC, Starli0n commented on settings/temporarycontainers.json
> +					"install_url": "https://addons.mozilla.org/firefox/downloads/file/3623550/temporary_containers-1.9.1-fx.xpi",
Done

2020-10-06 09:14 UTC, Starli0n commented on settings/trackingprotection.json
> +            "privacy.trackingprotection.cryptomining.enabled": true
I do not know you position regarding features that are enable by default.

For now, I let them to be sure that they are present in the generated file regardingless their default value set by Firefox which might change in a future release. 

Like that we are sure that the configuration is always compliant with the policies defined by the user.

2020-10-06 09:18 UTC, Starli0n commented on settings/media_devices.json
> +            "media.eme.enabled": false,
Sorry, I added two more features for that

2020-10-06 09:21 UTC, Starli0n commented on settings/prefetch_next.json
> +            "network.dns.disablePrefetchFromHTTPS": true,
As I did not know, I let it for now

2020-10-06 09:23 UTC, Starli0n commented
Could you please review my changes ?

2020-10-06 09:54 UTC, allo- reviewed
Your commit also includes a permission change on umatrix without changing the file itself. It would be good to remove this change as well.

I see a lot of different permissions on the files and maybe this should be unified sometimes, but that should be an own commit. Here umatrix.json permissions should not be changed, to avoid having this commit in its history even when the file was not changed.

2020-10-06 09:54 UTC, allo- commented on Dockerfile
> +# docker run -it --rm --name profilemaker -v $PWD:/code -w /code python:3.8.5-alpine3.12 /bin/sh
Are you mixing commits here? The commit description is also about the dockerfile.

2020-10-06 09:54 UTC, allo- commented on settings/clearurls.json
> +        "help_text": "Will automatically remove tracking elements from URLs to help protect your privacy when browsing through the Internet.",
I think something like "**This addon** will ..." is nicer to read.

2020-10-06 09:54 UTC, allo- commented on settings/prefetch_next.json
> +            "network.dns.disablePrefetchFromHTTPS": true,
As far as I see, `disablePrefetchFromHTTPS` disables it for HTTPS only (assuming https mean its a more confidential site) and `disablePrefetch` is the master kill switch.

Having both does not hurt, I just try to avoid to have too many redundant settings, because the goal is to generate something that is more transparent than just a user.js dump.

I guess we can leave it in for now. Probably mozilla will sooner or later unify them as the web becomes almost https-only.

2020-10-06 09:54 UTC, allo- commented on settings/referer.json
> +                "network.http.referer.XOriginTrimmingPolicy": 2
I think `XOriginTrimmingPolicy` should be completely removed in this section. It only causes confusion if the referer will be trimmed or disabled.

2020-10-06 09:54 UTC, allo- commented on settings/trackingprotection.json
> +            "privacy.trackingprotection.cryptomining.enabled": true
It depends a bit. Here we have a case that cannot hurt but is redundant.

- Redundant settings make the generated config harder to understand and the settings look like they do more than they actually do. For developers they hide what the main setting is about.
- Changing some defaults can hurt. Set "safe defaults" for TLS now and your browser will have unsafe non-default settings when Mozilla mitigates the next TLS security issue.
- Settings that are exposed in the UI can be changed there. For example you do not need a setting to turn off geo location, as Firefox asks for each site and allows to disable it globally from an easy to reach UI.

After all, I try to avoid generating a huge "trust me this are good settings" dump, but have it as transparent as possible which settings are generated for which reason.

2020-10-06 09:54 UTC, allo- commented on profiles/01_default.json
> +            "media_widevinecdm.json",
Is there an indication that DRM is used for tracking?

I think the point in not having the setting yet (even when I thought we had it) probably was that it is exposed to the user when a site with DRM is encounted the first time ("do you like to install additional software to play copy protected content") and has UI settings (for the DRM setting, not for widevine setting).

I think when we add this, it is rather useful in "Browser Features", if there isn't a source that backs that it is used for tracking.

2020-10-06 12:28 UTC, Starli0n commented on settings/clearurls.json
> +        "help_text": "Will automatically remove tracking elements from URLs to help protect your privacy when browsing through the Internet.",
OK I fixed it

2020-10-06 12:30 UTC, Starli0n commented on Dockerfile
> +# docker run -it --rm --name profilemaker -v $PWD:/code -w /code python:3.8.5-alpine3.12 /bin/sh
Sorry, I undo 2 commits instead of the last one, I fixed it

2020-10-06 12:44 UTC, Starli0n commented on profiles/01_default.json
> +            "media_widevinecdm.json",
My source is https://www.privacytools.io/browsers and I do not have any other source that shows that DRM is used for tracking.

I moved the two features to "Browser Features".

2020-10-07 12:12 UTC, Starli0n commented
Could you please review my new changes ?

2020-10-07 13:04 UTC, allo- requested changes
- cookieautodelete still has only a permission change and would be in the commit without a relevant change. Can you change it back to 644 before committing?
- The `XOriginTrimmingPolicy` is not resolved. The option adds an redundant setting making it unclear which setting takes precedence. For `XOriginPolicy: 2` there should be no other settings set.
- Maybe you can set the rights for the *modified* files all to 644 (default for non-executable files) instead of 755 (default for executables). Do not use `chmod 644 *` as there are other files with inconsistent rights that should not be in this commit. I think this should be unified in another commit that only changes rights.

I am not sure with the rights, if your editor sets them somehow. It does not seem to change it on README.md, but your json files are all changed to have the executable bit set.

I think the rest can be merged as it is now.

2020-10-07 16:18 UTC, Starli0n commented
- I undo the permissions of cookieautodelete (and another file that was trailing)
- I removed XOriginTrimmingPolicy
- I did a chmod 644 only on the new files

As for the rights, I guess that I made a copy/paste of other files that have bad rights

2020-10-07 16:22 UTC, Starli0n commented
Sorry for the issue regarding rights.

It should be ok by now ?

2020-10-07 16:25 UTC, merged

2020-10-07 16:33 UTC, allo- commented
The addon IDs seem to be wrong. I try to fix it.

2020-10-07 16:37 UTC, allo- commented
- FirefoxMulti-AccountContainers\@mozilla.org.xpi @testpilot-containers.xpi
- TemporaryContainers\@stoically.xpi '{c607c8df-14a7-4f28-894f-29e8722976af}'.xpi
- ClearURLs ??? (no id in manifest)

2020-10-08 08:10 UTC, Starli0n commented
Sorry, I did not know where to find their respective exact name / IDs of each extension

2020-10-08 08:15 UTC, allo- commented
No problem, now it works.

That's one of the reasons why enterprise policies work much smoother. I would wish you could install one on per profile basis instead of just one per Firefox installation (for all users).